#!/usr/bin/env bash
# Regenerate the world fixture gate-m9-client.sh joins.
#
# WHY THIS EXISTS. The fixture rots, silently and expensively. The one it replaces had been generated by a pack
# that included Terralith; the merged pack does not, so every one of its chunks referencing a terralith biome
# logged `Recoverable errors when loading section [x,y,z]: (Unknown registry key … terralith:… -> using default)`.
# That was 387 of the run's 401 ERROR lines — a 96% noise floor on the one log this project reads most, and it
# survived for months because nobody could regenerate the world without clicking through the client.
#
# So: generate it from a DEDICATED SERVER, headless, with the pack's worldgen mods and nothing else. Worldgen
# mods only, deliberately — a content mod contributes nothing to terrain but everything to the odds of the
# generator failing to boot, and the client that later opens this world has the full pack anyway (a save may be
# opened by a superset of the mods that wrote it; the reverse is what rots).
#
# Usage: [WORLD=NeoForbricTest] [TARGET=<rundir>] ./make-test-world.sh
#   Refuses to overwrite an existing save — move it aside yourself, so this can never eat a world you wanted.
set -uo pipefail
. "$(cd "$(dirname "$0")" && pwd)/lib.sh"   # record_server_pid / await_server / reap_stale_server

HERE="$(cd "$(dirname "$0")" && pwd)"
WORLD="${WORLD:-NeoForbricTest}"
TARGET="${TARGET:-$KERNEL/run/client-merged-pack}"
GEN="$KERNEL/run/server-worldgen"
SRC_MODS="${SRC_MODS:-$TARGET/mods}"

# The worldgen mods of the merged pack. Add to this list when the pack gains one, or the fixture stops matching
# the terrain the client generates at its edges.
WORLDGEN_PATTERNS="tectonic lithostitched"

[ -d "$SRC_MODS" ] || { echo "[make-world] no mods dir at $SRC_MODS" >&2; exit 2; }
if [ -e "$TARGET/saves/$WORLD" ]; then
  echo "[make-world] $TARGET/saves/$WORLD already exists — move it aside first (this script never deletes a save)" >&2
  exit 3
fi

rm -rf "$GEN"; mkdir -p "$GEN/mods"
for pat in $WORLDGEN_PATTERNS; do
  found=0
  for jar in "$SRC_MODS"/*"$pat"*.jar; do
    [ -f "$jar" ] || continue
    # A pack can carry both loaders' builds of one mod; the server runs the Forge-family side.
    case "$(basename "$jar")" in *fabric*) continue;; esac
    cp "$jar" "$GEN/mods/"; found=1
  done
  [ "$found" = 1 ] || echo "[make-world] NOTE no jar matching '$pat' in $SRC_MODS — terrain may not match the pack" >&2
done
echo "[make-world] generating with: $(ls "$GEN/mods" | paste -sd' ' -)"

printf 'level-name=%s\nserver-port=%s\nonline-mode=false\nmax-tick-time=-1\nview-distance=6\nspawn-protection=0\nsync-chunk-writes=false\n' "$WORLD" "$GATE_PORT" > "$GEN/server.properties"
printf 'eula=true\n' > "$GEN/eula.txt"

# Drive it through the same PID-based lifecycle the gates use, NOT a bare pipe. Measured the hard way: the first
# version of this script was `( sleep 75; echo save-all; sleep 10; echo stop ) | launch-kernel-server.sh`; the
# world generated and saved correctly — and the server was still running nine minutes later. Closing stdin does
# not stop a Minecraft server, and nothing here was watching. await_server bounds the wait and then guarantees
# the process is gone, by the pid this script recorded and no other — another session may be running its own.
reap_stale_server "$GEN"
( sleep 75; echo "save-all"; sleep 10; echo "stop" ) | RUNDIR="$GEN" "$HERE/launch-kernel-server.sh" > "$GEN/generate.log" 2>&1 &
GENPID=$!
record_server_pid "$GEN" "$GENPID"
await_server "$GENPID" "$GEN/generate.log" 180 30
rm -f "$GEN/.neoforbric-gate.pid"

if [ ! -f "$GEN/$WORLD/level.dat" ]; then
  echo "[make-world] FAILED — no level.dat; see $GEN/generate.log" >&2
  exit 4
fi

mkdir -p "$TARGET/saves"
cp -R "$GEN/$WORLD" "$TARGET/saves/$WORLD"
rm -f "$TARGET/saves/$WORLD/session.lock"
echo "[make-world] $TARGET/saves/$WORLD  ($(du -sh "$TARGET/saves/$WORLD" | cut -f1), $(find "$TARGET/saves/$WORLD" -name '*.mca' | wc -l | tr -d ' ') region file(s))"
echo "[make-world] verify with: $HERE/gate-m9-client.sh"
