/*
 * Copyright 2026 The NeoForbric Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.neoforbric.kernel.runtime;

import java.util.Map;

import it.unimi.dsi.fastutil.ints.AbstractInt2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.objects.ObjectSet;
import it.unimi.dsi.fastutil.objects.ObjectOpenHashSet;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.resources.Identifier;

/**
 * Makes {@code ParticleResources}' vanilla-typed {@code providers} map a live view of the NeoForge-typed one.
 *
 * <p>Vanilla 26.2 declares {@code providers} as {@code Int2ObjectMap<ParticleProvider<?>>} keyed by the particle
 * type's registry id. NeoForge 26.2.0.88 RE-TYPES that same field to {@code Map<Identifier, ParticleProvider<?>>}.
 * Same name, different descriptor is legal in the JVM, so the merged base carries BOTH — and the surviving
 * {@code <init>} writes only NeoForge's. The vanilla-typed one is null forever.
 *
 * <p>That is not a dormant curiosity. fabric-api's {@code DirectParticleProviderRegistry.register} reads the field
 * DIRECTLY — a raw {@code getfield providers:Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;}, then
 * {@code BuiltInRegistries.PARTICLE_TYPE.getId(type)}, then {@code put(int, provider)}. It never goes through
 * {@code getProviders()}, so no amount of rewriting the accessors reaches it. Any mod using the Fabric particle
 * API therefore NPEs inside {@code Minecraft.<init>}; here it was {@code particle-effects}.
 *
 * <p>So the field is given a value, and the value has to be a VIEW rather than a second map: the two halves of the
 * mechanism have to stay one map. A write through the int-keyed side must be visible to
 * {@code ParticleEngine.makeParticle}, which reads the {@code Identifier}-keyed one, and vice versa. The key
 * adaptation is the registry itself, which is the same thing each side already does — fabric-api spells
 * {@code getId(type)} and the merged {@code register} spells {@code getKey(type)}.
 *
 * <p>The view holds the live map BY REFERENCE, which is sound because {@code providers:Ljava/util/Map;} is final
 * and has exactly one {@code PUTFIELD} in the whole class, in {@code <init>}; nothing, reload included, replaces
 * it. The transformer that installs this refuses to run if that ever stops being true.
 */
public final class KernelParticleProviders {

	private KernelParticleProviders() {
	}

	/**
	 * Wraps the {@code Identifier}-keyed provider map as an {@code Int2ObjectMap}.
	 *
	 * <p>Declared as {@code Object} on purpose. Every game-side seam in {@link net.neoforbric.kernel.runtime} is
	 * expressed in JDK types so {@code KernelRuntimeClasses} can state its signature without the boot side
	 * needing the game's libraries on its classpath; the caller is generated bytecode, which supplies its own
	 * {@code CHECKCAST}.
	 */
	public static Object intKeyedView(Map<?, ?> byName) {
		@SuppressWarnings("unchecked")
		Map<Identifier, Object> live = (Map<Identifier, Object>) byName;
		return new IntKeyedView(live);
	}

	/**
	 * An {@code Int2ObjectMap} face on an {@code Identifier}-keyed map, translating through the particle registry.
	 *
	 * <p>Deliberately not spelled with its nested name anywhere in {@code src/main}: the registry test scans for
	 * {@code net.neoforbric.kernel.runtime.<Name>} and would then demand its own entry for this class.
	 */
	static final class IntKeyedView extends AbstractInt2ObjectMap<Object> {
		private static final long serialVersionUID = 1L;

		private final Map<Identifier, Object> byName;
		/**
		 * Entries whose int key names no registered particle type. They cannot be translated, and dropping them
		 * would lose a registration silently; they live here instead, readable through this face only.
		 */
		private final Int2ObjectOpenHashMap<Object> untranslatable = new Int2ObjectOpenHashMap<>();
		private boolean warned;

		IntKeyedView(Map<Identifier, Object> byName) {
			this.byName = byName;
		}

		private Identifier key(int id) {
			ParticleType<?> type = BuiltInRegistries.PARTICLE_TYPE.byId(id);
			return type == null ? null : BuiltInRegistries.PARTICLE_TYPE.getKey(type);
		}

		@Override
		public Object get(int id) {
			Identifier key = key(id);
			return key == null ? untranslatable.get(id) : byName.get(key);
		}

		@Override
		public Object put(int id, Object provider) {
			Identifier key = key(id);
			if (key == null) {
				// byId answers null for an id no particle type holds. Keeping the entry beats losing it: the
				// caller would see a successful put either way, and a lost provider is a particle that never
				// renders with nothing said about it.
				if (!warned) {
					warned = true;
					System.out.println("[NeoForbric/Particles] a provider was registered under particle id " + id
							+ ", which no registered particle type holds — kept, but nothing reading the "
							+ "Identifier-keyed map will see it");
				}
				return untranslatable.put(id, provider);
			}
			return byName.put(key, provider);
		}

		@Override
		public boolean containsKey(int id) {
			Identifier key = key(id);
			return key == null ? untranslatable.containsKey(id) : byName.containsKey(key);
		}

		@Override
		public Object remove(int id) {
			Identifier key = key(id);
			return key == null ? untranslatable.remove(id) : byName.remove(key);
		}

		@Override
		public int size() {
			return byName.size() + untranslatable.size();
		}

		/**
		 * Iteration translates back the other way. Particle ids are assigned when the built-in registry freezes at
		 * bootstrap, long before {@code Minecraft.<init>}, so the round trip is stable by the time anything here
		 * runs; an entry whose {@code Identifier} is no longer registered is skipped rather than reported as id 0.
		 */
		@Override
		public ObjectSet<Int2ObjectMap.Entry<Object>> int2ObjectEntrySet() {
			ObjectSet<Int2ObjectMap.Entry<Object>> out = new ObjectOpenHashSet<>();
			for (Map.Entry<Identifier, Object> e : byName.entrySet()) {
				ParticleType<?> type = BuiltInRegistries.PARTICLE_TYPE.getValue(e.getKey());
				if (type == null) continue;
				out.add(new AbstractInt2ObjectMap.BasicEntry<>(
						BuiltInRegistries.PARTICLE_TYPE.getId(type), e.getValue()));
			}
			for (Int2ObjectMap.Entry<Object> e : untranslatable.int2ObjectEntrySet()) {
				out.add(new AbstractInt2ObjectMap.BasicEntry<>(e.getIntKey(), e.getValue()));
			}
			return out;
		}
	}
}
